{
 "title": "Magi",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "synced", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Finalized Head",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "finalized_head", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Safe Head",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "safe_head", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (mode,cpu) (\n  100 - 100 * rate(node_cpu_seconds_total{mode=\"idle\"}[10s])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[10s]) + avg_over_time(node_memory_Cached_bytes[10s]) + avg_over_time(node_memory_Buffers_bytes[10s])) / avg_over_time(node_memory_MemTotal_bytes[10s])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Challenger: Output Root mismatches",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "root_mismatch", "legendFormat": "__auto" }
   ]
  }
 ]
}